### ISSUE TITLE
Example site needs more hosts and guests

### ISSUE THREAD

**Issue by vichudson1** [BubbleSort-Empire/empire#17]
We need more guests and hosts and all episodes and shows should be updated to include them.

**Comment by fluentinstroll** [comment]
good morning! I'd love to help you out with this

are there any particular hosts or guests you'd like?

**Comment by vichudson1** [comment]
@fluentinstroll, thanks for your enthusiasm for the project and wanting to help. Unfortunately at this time we aren’t quite ready for PRs just yet. The project is still in early stages and very much in flux. @scottaw66 and I are just using issues to track the tasks we need to complete as we work on the theme.

**Comment by scottaw66** [comment]
This is done
