### ISSUE TITLE
Support For Announcements

### ISSUE THREAD

**Issue by vichudson1** [BubbleSort-Empire/empire#24]
We need to add support for network announcements.

Ideally this would display on the home page, but could also be added to other pages as well as having a page to list previous announcements.

I'm proposing a new type, announcement, the would have metadata fields for post date and an expiration date as well as markdown for the announcement content. They will go into their own folder and have their own layout for an announcements list page.

The home page layout should be edited to include a section near the top that that will only be visible when there is an announcement where the site build date is between the announcement post date and expiration date. Any other time the section of the page should simply not be rendered.

Announcements will live on the announcements list page in perpetuity regardless of expiration date.

**Comment by scottaw66** [comment]
Do you want these to NOT show up on the blog?

**Comment by vichudson1** [comment]
I see them as separate, but that's negotiable if you think it's the wrong call.

**Comment by vichudson1** [comment]
@scottaw66 took care of this. Closing.
